language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: Wie5IWwStQ/OQA9vsrltAFqFGPLCYK6d2723iGKjo5KUsoaxkH2WNIAmmssd8uG9nUf870wkhmRCVUNhsR7mLb4AApYRgwTNseKxHkAdHqM7l6+D5KcM1+4bmU28gcvK0dCrZo9YrvKP/+Bilq+7zDmg0ZuJwbxa/cCs/tAXp17sMR6KkjqQriwKlB1JAcK+YANPtnXcNCQse6ePZoTwYosJ/SvO1/k9nPvbFFv5VaebxlGYCmy44Fc05ull9n9TsVYhdiNZLY2JQ301O8xEf8udwdn8SUO2xdb/Mii+GgbaIv3w3jlPEm8lnSmZNTdRrd04bHiU+PM9npGFoBKxZ9QY3+wfc80uwVH0MAI3vR/fi0ndU7hyv7QjGocwZJ/1tk3Eq2KLK13g6o6Ueubm7MAJie0h0YWAkg2LdauvJsUc6L41Sb1YGCdPk/0PnzemVW6zWcNkFmhDJbxB8wBL1wjM50VEA99YuPji5UHSvdrh3bqMXY4AcQ8UBo74FcX/w93hNTMHsRhE54nHCjjsBmyEGVlDqSlQfPw9P6Yj7CU9NEzPSaqHO9ncu2ePNCehlSnKOFmlJaGr+RcinZy0MEHQQASo8NNEdoFYI4tpsFpSRifRg2ubMcUo8fh9EiBzNgbkjBux5AgqlxbHyXRD+DpVJTz06s6EIuEG2pQDFb4=
  app: tony-addressbook
  on:
    repo: Toooooooony/addressbook
    branch: tod​o_tasks
